### ISSUE TITLE
tensorflow2.3.1 run error

### ISSUE THREAD

**Issue by jackweiwang** [aliprf/ASMNet#4]
run python main.py 

`txt
ValueError: Unknown loss function: asm_assisted_loss 
`

**Comment by aliprf** [comment]
The 'asm_assisted_loss' has been defined in **Asm_assisted_loss.py**. Please provide more information about the error.

**Comment by jackweiwang** [comment]
tensorflow cpu
(base) ubuntu@VM-0-17-ubuntu:~/work/ASMNet$ python main.py 
2021-11-14 10:41:44.367333: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/ubuntu/lib:/home/ubuntu/lib:
2021-11-14 10:41:44.367380: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-11-14 10:41:46.236439: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/ubuntu/lib:/home/ubuntu/lib:
2021-11-14 10:41:46.236485: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2021-11-14 10:41:46.236511: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (VM-0-17-ubuntu): /proc/driver/nvidia/version does not exist
2021-11-14 10:41:46.236900: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-14 10:41:46.245442: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2595120000 Hz
2021-11-14 10:41:46.245600: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ad59152750 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-11-14 10:41:46.245623: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    pretrained_model_path='./pre_trained_models/ASMNet/ASM_loss/ASMNet_300W_ASMLoss.h5')
  File "/home/ubuntu/work/ASMNet/test.py", line 26, in test_model
    model = tf.keras.models.load_model(pretrained_model_path)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 182, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 194, in load_model_from_hdf5
    training_config, custom_objects))
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 217, in compile_args_from_training_config
    loss = _deserialize_nested_config(losses.deserialize, loss_config)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 265, in _deserialize_nested_config
    return [_deserialize_nested_config(deserialize_fn, obj) for obj in config]
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 265, in <listcomp>
    return [_deserialize_nested_config(deserialize_fn, obj) for obj in config]
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 258, in _deserialize_nested_config
    return deserialize_fn(config)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/losses.py", line 1854, in deserialize
    printable_module_name='loss function')
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 378, in deserialize_keras_object
    'Unknown ' + printable_module_name + ': ' + object_name)
ValueError: Unknown loss function: asm_assisted_loss

**Comment by jackweiwang** [comment]
> The 'asm_assisted_loss' has been defined in **Asm_assisted_loss.py**. Please provide more information about the error.
 Hi @aliprf  this


(base) ubuntu@VM-0-17-ubuntu:~/work/ASMNet$ python main.py 
2021-11-14 12:04:13.975898: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/ubuntu/lib:/home/ubuntu/lib:
2021-11-14 12:04:13.975938: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-11-14 12:04:15.929290: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/ubuntu/lib:/home/ubuntu/lib:
2021-11-14 12:04:15.929337: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2021-11-14 12:04:15.929364: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (VM-0-17-ubuntu): /proc/driver/nvidia/version does not exist
2021-11-14 12:04:15.929825: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-14 12:04:15.936811: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2595120000 Hz
2021-11-14 12:04:15.937093: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5628e859ba40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-11-14 12:04:15.937120: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    pretrained_model_path='./pre_trained_models/ASMNet/ASM_loss/ASMNet_300W_ASMLoss.h5')
  File "/home/ubuntu/work/ASMNet/test.py", line 26, in test_model
    model = tf.keras.models.load_model(pretrained_model_path)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 182, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 194, in load_model_from_hdf5
    training_config, custom_objects))
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 217, in compile_args_from_training_config
    loss = _deserialize_nested_config(losses.deserialize, loss_config)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 265, in _deserialize_nested_config
    return [_deserialize_nested_config(deserialize_fn, obj) for obj in config]
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 265, in <listcomp>
    return [_deserialize_nested_config(deserialize_fn, obj) for obj in config]
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 258, in _deserialize_nested_config
    return deserialize_fn(config)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/losses.py", line 1854, in deserialize
    printable_module_name='loss function')
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 378, in deserialize_keras_object
    'Unknown ' + printable_module_name + ': ' + object_name)
ValueError: Unknown loss function: asm_assisted_loss

**Comment by HaoLiuHust** [comment]
how do you solve this problem?
